name: .NET Build & Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore ./src/
    - name: Build
      run: dotnet build ./src/ --no-restore
    - name: Test
      run: dotnet test ./src/ --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./src/XmlSanitizer.CLI/ -c release -r ubuntu.18.04-x64 --self-contained --verbosity minimal
  release:

    runs-on: ubuntu-latest

    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - ./src/XmlSanitizer.CLI/bin/release/netcoreapp3.1/ubuntu.18.04-x64/publish/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
